"""remove the name field from airplane model

Revision ID: 00804ee4737e
Revises: de7d4223a43b
Create Date: 2023-08-04 12:25:18.674090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00804ee4737e'
down_revision = 'de7d4223a43b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airplanes', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airplanes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
