"""create some model

Revision ID: 0e304a993068
Revises: 
Create Date: 2023-08-04 10:35:23.542675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e304a993068'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_id_'), ['id_'], unique=False)

    op.create_table('airports',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_airports_id_'), ['id_'], unique=False)

    op.create_table('users',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id_'), ['id_'], unique=False)

    op.create_table('air_lines',
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('airport_id', sa.Integer(), nullable=True),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    with op.batch_alter_table('air_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_air_lines_id_'), ['id_'], unique=False)

    op.create_table('airplanes',
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('reg_number', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('economy_seats', sa.Integer(), nullable=True),
    sa.Column('business_seats', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('airport_id', sa.Integer(), nullable=True),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.id_'], ),
    sa.PrimaryKeyConstraint('id_'),
    sa.UniqueConstraint('reg_number')
    )
    with op.batch_alter_table('airplanes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_airplanes_id_'), ['id_'], unique=False)

    op.create_table('flights',
    sa.Column('airplane_id', sa.Integer(), nullable=False),
    sa.Column('departure_airport_id', sa.Integer(), nullable=False),
    sa.Column('arrival_airport_id', sa.Integer(), nullable=False),
    sa.Column('departure_date', sa.DateTime(), nullable=False),
    sa.Column('arrival_date', sa.DateTime(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('price_per_seat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('seat_available', sa.Integer(), nullable=False),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['airplane_id'], ['airplanes.id_'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['departure_airport_id'], ['airports.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flights_id_'), ['id_'], unique=False)

    op.create_table('bookings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('type_of_seats', sa.Enum('FIRST_CLASS', 'BUSINESS', 'ECONOMY', name='flighseattype'), nullable=False),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id_'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_id_'), ['id_'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_id_'))

    op.drop_table('bookings')
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flights_id_'))

    op.drop_table('flights')
    with op.batch_alter_table('airplanes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_airplanes_id_'))

    op.drop_table('airplanes')
    with op.batch_alter_table('air_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_air_lines_id_'))

    op.drop_table('air_lines')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id_'))

    op.drop_table('users')
    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_airports_id_'))

    op.drop_table('airports')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_id_'))

    op.drop_table('admin')
    # ### end Alembic commands ###
