"""made  modification in arrival_airport_id in flight model

Revision ID: 1d717eba7df4
Revises: 0e304a993068
Create Date: 2023-08-04 12:04:02.736888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d717eba7df4'
down_revision = '0e304a993068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_constraint('flights_airplane_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'airplanes', ['airplane_id'], ['id_'])
        batch_op.create_foreign_key(None, 'airports', ['arrival_airport_id'], ['id_'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('flights_airplane_id_fkey', 'airplanes', ['airplane_id'], ['id_'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
