"""made the change in seat available in flight model

Revision ID: 30dff89af2e0
Revises: 443edfb74eb4
Create Date: 2023-08-04 14:20:03.371123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30dff89af2e0'
down_revision = '443edfb74eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.alter_column('seat_available',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.alter_column('seat_available',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
