"""remmade some change in airplane model

Revision ID: 443edfb74eb4
Revises: 00804ee4737e
Create Date: 2023-08-04 12:32:24.009003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443edfb74eb4'
down_revision = '00804ee4737e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airplanes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('Description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airplanes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
